### ISSUE TITLE
ImportError: cannot import name 'ExecWrapper' from 'wrapper' (/home/UserName/.local/lib/python3.10/site-packages/wrapper/__init__.py)

### ISSUE THREAD

**Issue by drew0ps** [myback/helm-py#1]
Hi,

I really like the library, looking at the objects it does exactly what I want. However, I have a bit of an issue with the dependencies.

I am on: 
```
python3 --version
Python 3.10.12
```

I import the package and initialize the class into an object like so:

```
from helm_wrap import helm

def helm_template(helm_chart):
    helm_chart = helm.Helm()
    helm_chart.template()
```

Although when I run the code I run into this error:

```
/bin/python3 /home/myuser/codebase/project-helm-docker/helm_template.py
Traceback (most recent call last):
  File "/home/myuser/codebase/project-helm-docker/helm_template.py", line 2, in <module>
    from helm_wrap import helm
  File "/home/myuser/.local/lib/python3.10/site-packages/helm_wrap/helm.py", line 1, in <module>
    from wrapper import ExecWrapper
```

I have the wrapper dep installed by pip:

```
pip install wrapper
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wrapper in /home/myuser/.local/lib/python3.10/site-packages (1.1.0b1)
```

Could you lend a hand please?

**Comment by myback** [comment]
install requirements from requirements.txt file
```shell
pip install -r https://raw.githubusercontent.com/myback/helm-py/main/requirements.txt
```
or you can get the wrapper from https://github.com/myback/bin-wrapper
or just run `pip install helm-wrap`

**Comment by drew0ps** [comment]
Hi @myback ,

Thanks a lot for getting back to me and maintaining this repo.


I tried your suggestions but did not succeed just yet. I decided to create a venv to help troubleshooting this issue. These are the packages in the venv, all of them installed because they were required by the wrapper:
![status](https://github.com/myback/helm-py/assets/26969736/7a228243-89ca-4463-bebb-1ec0c88b0ac8)

Yet I still get this error:

```
Traceback (most recent call last):
  File "/home/User/codebase/project-helm-docker/helm_template.py", line 2, in <module>
    from helm_wrap import helm
  File "/home/User/codebase/.venv/lib/python3.12/site-packages/helm_wrap/helm.py", line 1, in <module>
    from wrapper import ExecWrapper
ImportError: cannot import name 'ExecWrapper' from 'wrapper' (/home/User/codebase/.venv/lib/python3.12/site-packages/wrapper/__init__.py)
```

**Comment by drew0ps** [comment]
Hi @myback,

I was trying to further troubleshoot this issue and dig a bit.

From the error message I can see that on the first line of helm.py we do:

``` 
from wrapper import ExecWrapper


class Helm(ExecWrapper):
    __command_aliases = {
        "hist": "history",
        "ls": "list"
    }
...
```

Although in the wrapper module wrapper.py I cannot find an ExecWrapper class, only a BinWrapper one.

**Comment by myback** [comment]
@dr-platform-devops 
that's right, I forgot that I renamed the class
`pip install helm-wrap==1.0.4`

**Comment by drew0ps** [comment]
I confirm that it works now - thanks a lot for the support and maintaining this repo.
